name: Build and Deploy to GKE

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Build the Docker image
    - name: Build
      run: |-
        docker build --tag "almir-school/node-web-app:latest" .


